const slides=[...document.querySelectorAll('.slide')];let currentSlide=0;const currentNumber=document.getElementById('currentNumber'),totalNumber=document.getElementById('totalNumber'),progressBar=document.getElementById('progressBar'),slideName=document.getElementById('slideName'),previousButton=document.getElementById('previousSlide'),nextButton=document.getElementById('nextSlide');if(totalNumber)totalNumber.textContent=String(slides.length).padStart(2,'0');
const sessions={
'ai-excel':{month:'JANUARY',title:'AI in Excel',speaker:'Alaa Dalghan',poster:'assets/ai-excel-january.jpg',description:'One of the first Learning Bites in our AI journey, showing how AI can make everyday Excel work faster, simpler and more insightful.',tags:['Excel','Productivity','AI']},
'copilot-intro':{month:'JANUARY',title:'Introduction to Microsoft Copilot',speaker:'Raghad Al-Hemeimat · Microsoft',poster:'assets/introduction-to-copilot-january.png',description:'A practical introduction to Microsoft Copilot and how AI can become a useful part of the way we work every day.',tags:['Microsoft Copilot','Everyday AI','Productivity']},
'copilot-excel':{month:'MARCH',title:'Copilot in Excel',speaker:'Raghad Al-Hemeimat · Microsoft',poster:null,description:'A hands-on look at using Copilot inside Excel and discovering how AI can support everyday data work.',tags:['Copilot','Excel','Microsoft']},
'ai-powerpoint':{month:'APRIL',title:'AI in PowerPoint',speaker:'Alaa Dalghan',poster:'assets/ai-powerpoint-april.png',description:'Exploring how AI can help us create clearer, sharper presentations in less time.',tags:['PowerPoint','Presentations','Productivity']},
'ai-leadership':{month:'MAY',title:'AI for Leaders',speaker:'Alaa Dalghan',poster:'assets/ai-leadership.jpg',description:'Exploring how leaders can use AI to think differently, make better-informed decisions and spot new opportunities.',tags:['Leadership','Decision-Making','Strategy']},
'bricks':{month:'MAY',title:'BRICKS AI',speaker:'Riverdale Institute',poster:'assets/bricks-ai-may.jpg',description:'A Finance Learning Bite exploring BRICKS AI and how AI can support financial analysis.',tags:['Finance','Financial Analysis','BRICKS AI']},
'legal':{month:'JUNE',title:'AI in Legal & Compliance',speaker:'Ramy Aldamati',poster:'assets/ai-legal-compliance-june.jpg',description:'A look at practical ways AI can support legal and compliance work.',tags:['Legal','Compliance','Business AI']},
'agent-one':{month:'JULY',title:'AI Agent 1',speaker:'Raghad Al-Hemeimat · Microsoft',poster:null,description:'The start of our AI Agent series — moving from using AI tools to understanding how an Agent can help with a specific task.',tags:['AI Agents','Microsoft','Automation']},
'agent-two':{month:'JULY',title:'AI Agent 2',speaker:'Raghad Al-Hemeimat · Microsoft',poster:null,description:'Taking the idea further and exploring how AI Agents can be designed around real business needs.',tags:['AI Agents','Business Solutions','Automation']},
'agent-three':{month:'JULY',title:'AI Agent 3',speaker:'Raghad Al-Hemeimat · Microsoft',poster:null,description:'Turning learning into ideas and encouraging employees to think about what they could build with AI in their own work.',tags:['AI Agents','Innovation','Building with AI']}}
function showSlide(index){if(index<0)index=slides.length-1;if(index>=slides.length)index=0;slides.forEach((s,i)=>{s.classList.toggle('active',i===index);if(i===index)s.scrollTop=0});currentSlide=index;if(currentNumber)currentNumber.textContent=String(index+1).padStart(2,'0');if(progressBar)progressBar.style.width=`${((index+1)/slides.length)*100}%`;if(slideName)slideName.textContent=slides[index].dataset.title||`Slide ${index+1}`;document.querySelectorAll('.overview-list button').forEach((b,i)=>b.classList.toggle('active',i===index));slides[index].querySelectorAll('.reveal').forEach((el,i)=>{el.style.animation='none';void el.offsetHeight;el.style.animation=`rise .55s ${Math.min(i*.035,.28)}s both`})}
const nextSlide=()=>showSlide(currentSlide+1),previousSlide=()=>showSlide(currentSlide-1);nextButton?.addEventListener('click',nextSlide);previousButton?.addEventListener('click',previousSlide);document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',nextSlide));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showSlide(Number(b.dataset.go))}));
document.addEventListener('keydown',e=>{const a=document.activeElement,isTyping=a&&['INPUT','TEXTAREA','SELECT'].includes(a.tagName);if(isTyping){if(e.key==='Escape')a.blur();return}if(['ArrowRight','PageDown'].includes(e.key)){e.preventDefault();nextSlide()}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();previousSlide()}if(e.key==='Home')showSlide(0);if(e.key==='End')showSlide(slides.length-1);if(e.key==='Escape'){closeOverview();closeSessionModal()}});
let sx=0;document.addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});document.addEventListener('touchend',e=>{const d=sx-e.changedTouches[0].screenX;if(Math.abs(d)>60)(d>0?nextSlide:previousSlide)()},{passive:true});
const overview=document.getElementById('overview'),overviewList=document.getElementById('overviewList');function buildOverview(){if(!overviewList)return;overviewList.innerHTML='';slides.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong>${s.dataset.title||`Slide ${i+1}`}</strong>`;b.addEventListener('click',()=>{showSlide(i);closeOverview()});overviewList.appendChild(b)})}function openOverview(){overview?.classList.add('open')}function closeOverview(){overview?.classList.remove('open')}document.getElementById('menuButton')?.addEventListener('click',openOverview);document.getElementById('closeOverview')?.addEventListener('click',closeOverview);overview?.querySelector('.overview-background')?.addEventListener('click',closeOverview);
const timelineData={JAN:{month:'JANUARY',title:'It started with the everyday',text:'We began with tools people already knew — Excel and Microsoft Copilot — and explored how AI could make everyday work a little easier.',progress:'0%'},MAR:{month:'MARCH',title:'Bringing AI into familiar work',text:'Next came Copilot in Excel, giving employees another practical way to try AI inside a tool they already use.',progress:'20%'},APR:{month:'APRIL',title:'Creating with AI',text:'With AI in PowerPoint, we explored how AI could help us turn ideas into clearer presentations, faster.',progress:'40%'},MAY:{month:'MAY',title:'Asking where else AI could help',text:'The conversation grew beyond productivity as we explored AI in leadership and financial analysis.',progress:'60%'},JUN:{month:'JUNE',title:'Taking AI across the business',text:'We continued exploring practical applications, including Legal & Compliance, and started thinking more deeply about real business needs.',progress:'80%'},JUL:{month:'JULY',title:'From using AI to building with it',text:'Our AI Agent Learning Bites changed the question from “What can AI do?” to “What can we build with it?”',progress:'100%'}};const timelineStops=document.querySelectorAll('.journey-stop'),timelineMonth=document.getElementById('timelineMonth'),timelineTitle=document.getElementById('timelineTitle'),timelineText=document.getElementById('timelineText'),journeyProgress=document.querySelector('.journey-progress');timelineStops.forEach(stop=>stop.addEventListener('click',()=>{const d=timelineData[stop.dataset.month];if(!d)return;timelineStops.forEach(x=>x.classList.remove('active'));stop.classList.add('active');if(timelineMonth)timelineMonth.textContent=d.month;if(timelineTitle)timelineTitle.textContent=d.title;if(timelineText)timelineText.textContent=d.text;if(journeyProgress)journeyProgress.style.width=d.progress}));
const sessionModal=document.getElementById('sessionModal'),modalPoster=document.getElementById('modalPoster'),posterPlaceholder=document.getElementById('posterPlaceholder'),modalMonth=document.getElementById('modalMonth'),modalTitle=document.getElementById('modalTitle'),modalSpeaker=document.getElementById('modalSpeaker'),modalDescription=document.getElementById('modalDescription'),modalTags=document.getElementById('modalTags');function openSessionModal(key){const d=sessions[key];if(!d||!sessionModal)return;if(modalMonth)modalMonth.textContent=d.month;if(modalTitle)modalTitle.textContent=d.title;if(modalSpeaker)modalSpeaker.textContent=d.speaker;if(modalDescription)modalDescription.textContent=d.description;if(modalTags)modalTags.innerHTML=d.tags.map(t=>`<span>${t}</span>`).join('');if(d.poster){modalPoster.src=d.poster;modalPoster.alt=d.title;modalPoster.style.display='block';if(posterPlaceholder)posterPlaceholder.style.display='none'}else{modalPoster.style.display='none';if(posterPlaceholder)posterPlaceholder.style.display='block'}sessionModal.classList.add('open')}function closeSessionModal(){sessionModal?.classList.remove('open')}document.querySelectorAll('[data-session]').forEach(el=>el.addEventListener('click',()=>openSessionModal(el.dataset.session)));document.getElementById('modalClose')?.addEventListener('click',closeSessionModal);document.querySelector('[data-close-modal]')?.addEventListener('click',closeSessionModal);
function patchContent(){
const brandMark=document.querySelector('.brand-mark');if(brandMark){brandMark.textContent='';brandMark.setAttribute('aria-label','Fine Hygienic Holding')}
const hero=document.querySelector('.hero-slide');if(hero){const p=hero.querySelector('.hero-intro');if(p)p.innerHTML='It started with a simple question: <strong>how can AI help us work better?</strong><br>From there, we started learning, experimenting and exploring.'}
const statement=document.querySelector('.statement-slide');if(statement){const h=statement.querySelector('.statement-title');if(h)h.innerHTML='AI is changing the way we work — <span>and we wanted our people to be part of that journey.</span>';const p=statement.querySelector('.statement-copy');if(p)p.textContent='Rather than jumping straight into solutions, we started by giving our employees the chance to learn, explore different tools and discover where AI could actually make a difference in their everyday work.';const e=statement.querySelector('.statement-emphasis');if(e)e.innerHTML='And that was just the beginning.'}
const process=document.querySelector('.process-slide');if(process){const h=process.querySelector('.section-heading h2');if(h)h.innerHTML='We started by <span>learning.</span>';const d=process.querySelector('.section-description');if(d)d.textContent='Our AI Learning Bites gave employees a simple, practical way to explore AI — from everyday productivity tools to business applications and AI Agents.';const ps=process.querySelectorAll('.process-card p');const txt=['Understand what AI can do.','See where it could help us.','Try it in our everyday work.','Turn ideas into real solutions.'];ps.forEach((p,i)=>{if(txt[i])p.textContent=txt[i]})}
const timeline=document.querySelector('.timeline-slide');if(timeline){const d=timeline.querySelector('.section-description');if(d)d.textContent='One session at a time, our understanding of AI kept growing — from everyday tools to business applications and eventually AI Agents.';const t=timeline.querySelector('#timelineTitle');if(t)t.textContent=timelineData.JAN.title;const tx=timeline.querySelector('#timelineText');if(tx)tx.textContent=timelineData.JAN.text}
const jun=document.querySelector('.journey-stop[data-month="JUN"] small');if(jun)jun.textContent='Business AI';const jul=document.querySelector('.journey-stop[data-month="JUL"] small');if(jul)jul.textContent='AI Agents';
const gallery=document.querySelector('.gallery-slide');if(gallery){const d=gallery.querySelector('.section-description');if(d)d.textContent='Ten sessions, each adding something new to the way we think about AI.'}
const cards=document.querySelectorAll('.session-card');cards.forEach(c=>{const d=sessions[c.dataset.session];if(!d)return;const m=c.querySelector('.session-month'),h=c.querySelector('h3'),p=c.querySelector('p');if(m)m.textContent=d.month.slice(0,3);if(h)h.textContent=d.title;if(p)p.textContent=d.speaker;if(d.poster){c.classList.add('has-poster');c.style.setProperty('--poster',`url("${d.poster}")`)}});
const productivity=document.querySelector('.showcase-slide');if(productivity){const h=productivity.querySelector('h2');if(h)h.innerHTML='We started with the tools <span>we already use every day.</span>';const p=productivity.querySelector('.showcase-intro');if(p)p.textContent='Our first Learning Bites showed employees how AI could make familiar tasks a little easier — from working in Excel to preparing presentations and using Microsoft Copilot.'}
const business=document.querySelector('.business-slide');if(business){const h=business.querySelector('.section-heading h2');if(h)h.innerHTML='Then we started asking: <span>where else could AI help?</span>';const descriptions=business.querySelectorAll('.business-content p');const bt=['Exploring how AI can support leaders, decisions and new ways of thinking.','Discovering how AI can support financial analysis in a practical way.','Looking at practical ways AI can support legal and compliance work.'];descriptions.forEach((p,i)=>{if(bt[i])p.textContent=bt[i]})}
const businessLeadership=document.querySelector('.business-card[data-session="ai-leadership"] h3');if(businessLeadership)businessLeadership.textContent='AI for Leaders';
document.querySelectorAll('.agent-series>div').forEach(d=>{const sm=d.querySelector('small');if(sm)sm.textContent='July'});
const agents=document.querySelector('.agents-slide');if(agents){const h=agents.querySelector('.agents-copy h2');if(h)h.innerHTML='Then came the next big step: <span>building with AI.</span>';const p=agents.querySelector('.agents-copy>p');if(p)p.innerHTML='Our AI Agent Learning Bites moved us from simply using AI tools to asking a new question: <strong>what can we build with them?</strong>'}
const impact=document.querySelector('.impact-slide');if(impact){const h=impact.querySelector('.impact-message h2');if(h)h.innerHTML='And then something important <span>started happening.</span>';const p=impact.querySelector('.impact-message p');if(p)p.textContent='People began connecting what they had learned to challenges they see in their own work. Ideas started becoming use cases — and some of those use cases started becoming real solutions.';const b=impact.querySelector('.primary-button');if(b)b.innerHTML='Meet Nadi <span>→</span>'}
const nadi=document.querySelector('.nadi-slide');if(nadi){const lead=nadi.querySelector('.nadi-lead');if(lead)lead.textContent='Nadi took what he learned through the AI journey and applied it to something very practical in HR.';const heads=nadi.querySelectorAll('.story-point strong');if(heads[0])heads[0].textContent='The Challenge';if(heads[1])heads[1].textContent='The Idea';if(heads[2])heads[2].textContent='The Solution';const pts=nadi.querySelectorAll('.story-point p');if(pts[0])pts[0].textContent='Preparing official employee letters can involve repetitive manual work.';if(pts[1])pts[1].textContent='What if an AI Agent could prepare the letter automatically?';if(pts[2])pts[2].textContent='Give the Agent the employee person number and tell it who the letter is for — the Agent prepares the official letter.'}
const demo=document.querySelector('.demo-slide');if(demo){const h=demo.querySelector('.demo-copy h2');if(h)h.innerHTML='From employee number <span>to official letter.</span>';const p=demo.querySelector('.demo-copy>p');if(p)p.textContent='A simple idea built around a real everyday need. The admin team enters the employee person number and selects who the letter is addressed to. The HR Agent prepares the official letter.';const labels=demo.querySelectorAll('.demo-flow span');if(labels[0])labels[0].textContent='Person Number';if(labels[1])labels[1].textContent='Who is it for?';if(labels[2])labels[2].textContent='Generate Letter';const fields=demo.querySelectorAll('.demo-field');if(fields[0]?.querySelector('label'))fields[0].querySelector('label').textContent='Person Number';if(fields[1]?.querySelector('label'))fields[1].querySelector('label').textContent='Letter Addressed To';const prompt=document.getElementById('agentPrompt')?.closest('.demo-field');prompt?.remove();const msg=demo.querySelector('.agent-message p');if(msg)msg.textContent='Hi! Enter the employee person number and tell me who the official letter is for.';const select=document.getElementById('letterParty');if(select){select.innerHTML='<option value="Bank">Bank</option><option value="Embassy">Embassy</option><option value="Other">Other</option>'}}
const closing=document.querySelector('.closing-slide');if(closing){const h=closing.querySelector('.closing-title');if(h)h.innerHTML='And we are only<br><span>getting started.</span>';const p=closing.querySelector('.closing-copy');if(p)p.innerHTML='The biggest outcome is not just learning new tools. It is seeing our people experiment, ask questions and start thinking differently about how work can be done.<br><strong>The next AI idea could come from you.</strong>'}
const pillars=document.querySelectorAll('.closing-pillars span');['LEARN','EXPERIMENT','APPLY','BUILD'].forEach((t,i)=>{if(pillars[i])pillars[i].textContent=t})}
function restoreOriginalNadiLayout(){const style=document.createElement('style');style.id='original-nadi-layout';style.textContent=`.nadi-layout{display:grid;grid-template-columns:.75fr 1.25fr;gap:7vw;align-items:center}.nadi-photo-wrap{height:590px;border-radius:34px;overflow:hidden;position:relative;box-shadow:0 30px 80px rgba(5,18,38,.14);background:transparent}.nadi-photo{width:100%;height:100%;object-fit:cover;object-position:center}.photo-number{position:absolute;left:18px;top:18px;z-index:4;width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:rgba(255,255,255,.88);color:#159a91;font-size:10px;font-weight:700;text-shadow:none}.photo-caption{position:absolute;left:20px;right:20px;bottom:20px;padding:17px;border-radius:18px;background:rgba(255,255,255,.88);backdrop-filter:blur(14px);display:flex;flex-direction:column;color:#101827}.photo-caption span{color:#159a91;font-size:8px;letter-spacing:.16em}.photo-caption strong{margin-top:6px;font:700 22px "Space Grotesk"}.photo-caption small{margin-top:3px;color:#6f7887}.nadi-lead{max-width:630px;color:#6f7887;font-size:18px}.story-points{margin-top:28px;margin-bottom:0}.story-point{display:grid;grid-template-columns:45px 1fr;gap:15px;padding:17px 0;border-top:1px solid rgba(16,24,39,.12);border-bottom:0}.story-point>span{color:#159a91;font-size:9px;font-weight:700;padding-top:0}.story-point strong{display:block;font:600 17px "Space Grotesk";color:#101827}.story-point p{margin:4px 0 0;color:#6f7887;font-size:12px}@media(max-height:820px) and (min-width:1001px){.nadi-photo-wrap{height:480px}}@media(max-width:1000px){.nadi-layout{grid-template-columns:1fr}.nadi-photo-wrap{height:520px}}`;document.head.appendChild(style)}
function setupDemo(){const btn=document.getElementById('generateLetter'),num=document.getElementById('employeeNumber'),party=document.getElementById('letterParty'),chat=document.getElementById('demoChat');btn?.addEventListener('click',()=>{if(!num?.value.trim()||!party?.value){if(chat)chat.innerHTML+='<div class="agent-message"><div class="message-avatar">AI</div><div><strong>HR Agent</strong><p>Please enter the person number and select who the letter is addressed to.</p></div></div>';return}btn.disabled=true;btn.querySelector('span').textContent='Preparing...';setTimeout(()=>{if(chat)chat.innerHTML=`<div class="agent-message"><div class="message-avatar">AI</div><div><strong>HR Agent</strong><p>Employee found. I’m preparing the official letter addressed to <b>${party.value}</b> for person number <b>${num.value.trim()}</b>.</p><p style="color:#39a99f;font-weight:700">Ready for admin review · Demo generated</p></div></div>`;btn.disabled=false;btn.querySelector('span').textContent='Generate Letter'},650)})}
patchContent();restoreOriginalNadiLayout();buildOverview();setupDemo();showSlide(0);